name: ci
on:
  push:
    branches:
      - master
      - try
  pull_request:
jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
      - uses: DeterminateSystems/nix-installer-action@v2
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: parse
        run: nix-instantiate --json --parse ./**/*.nix
      - name: lints
        run: |
          nix build -L --keep-going \
            .\#checks.x86_64-linux.pre-commit-check
  build-host:
    name: build-${{ matrix.host.name }}
    runs-on: ${{ matrix.host.ghSystem }}
    needs: get-hosts
    strategy:
      fail-fast: false
      matrix:
        host: ["x86_64-linux"]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
      - uses: DeterminateSystems/nix-installer-action@v2
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: build-host
        run: |
          nix run nixpkgs#nix-build-uncached -- \
            --keep-going \
            -A packages.${{ matrix.host.hostPlatform }}.wsl
