name: update-flakes
on:
  schedule:
    - cron:  '*/120 * * * *'
  workflow_dispatch:
jobs:
  get-flakes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-flakes.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
      - uses: DeterminateSystems/nix-installer-action@v2
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - id: get-flakes
        run: |
          get_flake_inputs() {
            nix flake metadata --json \
              | jq -c '
                  .locks.nodes.root.inputs
                  | {flake: keys}'
          }

          echo "matrix=$(get_flake_inputs)" >> "$GITHUB_OUTPUT"

  update-flake:
    name: update-${{ matrix.flake }}
    runs-on: ubuntu-latest
    needs: get-flakes
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-flakes.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
      - uses: DeterminateSystems/nix-installer-action@v2
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.email "luciofranco14@gmail.com"
      - run: git config --global user.name "Lucio Franco"
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v19
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          pr-labels: |                  # Labels to be set on the PR
            dependencies
            automated 
